<?php
function portlet_block_options() {
  $args = array();
  $options = array();

  $result = db_query('SELECT arg FROM {portlet_config} WHERE type="block";');
  while ($arg = db_fetch_array($result)) {
      $args[] = $arg['arg'];
  }

  $result = db_query('SELECT boxes.bid AS bid, boxes.info AS info, blocks.title AS title FROM {boxes} LEFT JOIN {blocks} ON boxes.bid = blocks.delta WHERE blocks.module = "block";');

  while ($block = db_fetch_object($result)) {
		 $block_title = (! empty($block_title)) ? $block->title : $block->info;
		 $options['block:'.$block->bid] = $block_title;
  }

  return array('Block' => $options);
}

function theme_portlet_block($pid, $title, $bid, $count, $state, $countable) {
  $block = db_fetch_array(db_query('SELECT bl.title, bx.body, bx.format FROM {boxes} AS bx LEFT JOIN {blocks} AS bl ON bx.bid = bl.delta WHERE bx.bid=%d AND bl.module = "block"', $bid));
  // If block have title use title of portlet and normal portlet theme
  // If haven't use empty_portlet theme
  $content = check_markup($block['body'], $block['format'], FALSE);
  $theme = ($block['title']) ? 'portlet' : 'portlet_empty';
  return theme($theme, $pid, $title, $content, $state, $countable, 'block', $count);
}

function portlet_block_theme() {
  $items['portlet_block'] = array(
    'arguments' => array()
  );
  return $items;
}
?>
