<?php
function portlet_menu_options() {
  $options = array();

  // Take alphabetical all taxonomies in system
  $result = db_query('SELECT menu_name, title FROM {menu_custom} ORDER BY title;');
  while ($menu = db_fetch_array($result)) {
      $options['menu:'. $menu['menu_name']] = $menu['title'];
  }
  return array('Menu' => $options);
}

function theme_portlet_menu($pid, $title, $name, $count, $state, $countable) {
  $menu = menu_load($name);
  // For now we use portlet title instead menu title
  // $title = $menu['title'];
  $content = menu_tree($name);
  return theme('portlet', $pid, $title, $content, $state, $countable, 'menu', $count);
}

function portlet_menu_theme() {
  $items['portlet_menu'] = array(
    'arguments' => array()
  );
  return $items;
}
?>
