<?php
function portlet_menu_options() {
  $options = array();

  // Take alphabetical all taxonomies in system
  $result = db_query('SELECT menu_name, title FROM {menu_custom} ORDER BY title;');
  while ($menu = db_fetch_array($result)) {
      $options['menu:'. $menu['menu_name']] = $menu['title'];
  }
  return array('Menu' => $options);
}

function theme_portlet_menu($pid, $title, $name, $count, $state, $countable) {
  $menu = menu_load($name);
  // For now we use portlet title instead menu title
  $elements = menu_tree_all_data($name);
	$content = '<ul class="zhr-menu">';
	$i = 0;
	foreach ($elements as $element) {
		if (check_plain($element['link']['title'])) {
			if ($i > 0) { $content .= '<li class="portlet-node-separator"><div class="portlet-node-separator-fill">&nbsp;</div></li>'; }
			$content .= '<li><a href="'.check_plain($element['link']['link_path']).'">'. check_plain($element['link']['title']).'</a></li>';
			++$i;
		}
	}
	$content .= '</ul>';
  return theme('portlet', $pid, $title, $content, $state, $countable, 'menu', $count);
}

function portlet_menu_theme() {
  $items['portlet_menu'] = array(
    'arguments' => array()
  );
  return $items;
}
?>
