<?php
function portlet_taxonomy_options() {
  $options = array();

  // Take alphabetical all taxonomies in system
  $result = db_query('SELECT tid, name FROM {term_data} ORDER BY name;');
  while ($term = db_fetch_array($result)) {
      $options['taxonomy:'.$term['tid']] = $term['name'];
  }
  return array('Taxonomy' => $options);
}

function portlet_taxonomy_count($pid) {
  $data = db_fetch_array(db_query('SELECT COUNT(tn.tid) AS quantity FROM {term_node} AS tn RIGHT JOIN {portlet_config} AS pc ON tn.tid = pc.arg WHERE pc.pid = %d', $pid));
  return $data['quantity'];
}

function portlet_taxonomy_content($tid, $count) {
  $i = 0;
  $output = '<ul class="portlet-node-list">';
  $tids = array($tid);
  $result = taxonomy_select_nodes($tids);
  while (($node = db_fetch_object($result)) AND ($i < $count)) {
    $node = node_build_content(node_load($node->nid));
    $output .= '<li>';
    $output .= '<a href="'.url('node/'.$node->nid).'" class="portlet-node-title"><h4>'.$node->title.'</h4></a>';
    $output .= '<p>';
    if ($node->thumbnail) {
      $output .= theme('image', $node->thumbnail, $node->thumbnail, $node->thumbnail);
    }
    $output .strip_tags($node->teaser).'</p>';
    $output .= '</li>';
    $i++;
  }
  $output .= '</ul>';
  return $output;
}

function theme_portlet_taxonomy($pid, $title, $tid, $count, $state, $countable) {
  $content = portlet_taxonomy_content($tid, $count);
  return theme('portlet', $pid, $title, $content, $state, $countable, 'taxonomy', $count);
}

function portlet_taxonomy_theme() {
  $items['portlet_taxonomy'] = array(
    'arguments' => array()
  );
  return $items;
}
?>
