<?php
function portlet_taxonomy_options() {
  $options = array();

  // Take alphabetical all taxonomies in system
  $result = db_query('SELECT tid, name FROM {term_data} ORDER BY name;');
  while ($term = db_fetch_array($result)) {
      $options['taxonomy:'.$term['tid']] = $term['name'];
  }
  return array('Taxonomy' => $options);
}

function portlet_taxonomy_count($pid) {
  $data = db_fetch_array(db_query('SELECT COUNT(tn.tid) AS quantity FROM {term_node} AS tn RIGHT JOIN {portlet_config} AS pc ON tn.tid = pc.arg WHERE pc.pid = %d', $pid));
  return $data['quantity'];
}

function portlet_taxonomy_content($tid, $count) {
  $i = 0;
	$output = '';
  $tids = array($tid);
  $result = taxonomy_select_nodes($tids);
  $output .= '<ul class="portlet-node-list">';
  while (($node = db_fetch_object($result)) AND ($i < $count)) {
		$node = node_build_content(node_load($node->nid));
		if ($i > 0) { $output .= '<li class="portlet-node-separator"><div class="portlet-node-separator-fill">&nbsp;</div></li>'; }
		$output .= '<li class="portlet-node-element">';
    $output .= '<a href="'.url('node/'.$node->nid).'" class="portlet-node-title"><h3>'.$node->title.'</h3></a>';
		$output .= '<span class="portlet-node-date">'.date('d/m/Y' ,$node->revision_timestamp).' -</span> <span class="portlet-node-author">'.$node->name.'</span>';
    if ($node->thumbnail) {
      $output .= theme('image', $node->thumbnail, $node->thumbnail, $node->thumbnail);
		}
		$content = (empty($node->teaser)) ? $node->body['#content'] : $node->teaser;
    $output .= '<p>'. $content.'</p>';
    $i++;
		$output .= '</li>';
  }
	$output .= '</ul>';
  return $output;
}

function theme_portlet_taxonomy($pid, $title, $tid, $count, $state, $countable) {
  $content = portlet_taxonomy_content($tid, $count);
  return theme('portlet', $pid, $title, $content, $state, $countable, 'taxonomy', $count);
}

function portlet_taxonomy_theme() {
  $items['portlet_taxonomy'] = array(
    'arguments' => array()
  );
  return $items;
}
?>
